### ISSUE TITLE
annotateTargets: Error: attempt to apply non-function

### ISSUE THREAD

**Issue by viktorlj** [mskilab/fish.hook#1]
Hi,

Thank you for sharing this algorithm.

I'm attempting to run your demo script using the supplied data but I'm running into some troubles and was wondering if this is something known. The following command generates an error message. 

```
anno = fish$annotateTargets(maxPtGene = 1, verbose = FALSE, PtIDCol = "patient_code")
Error: attempt to apply non-function
```

Two questions:
1. The function seems to be named annotate.targets in the manual, I don't know if this matters but is this only a typo?
2. According to the manual the Annotated-object used in later stages should be generated by calling FishHook$annotateTargets(). However, even if I swap to annotate.targets I can't seem to pass the fish variables into the function, it only responds with Error: attempt to apply non-function. I can use it by supplying the variables directly to the function but can't get the covariates to work (Error: object of type 'closure' is not subsettable when supplying the Covariates variable from c(rept). Do you have any input for this?

Working in R 3.4.2 on MacOS 10.12.6

Thanks

**Comment by ZoranZG** [comment]
Hello,

We are currently working on a major ui&qol overhaul and as such a majority of the documentation is in a state of limbo, I'm expecting to have the changes completed by this coming Monday (11/27/27) and will include updated demo/manual. Sorry for any inconvenience. 

In relation to your questions:
1. In the old version the command was named annotate.targets, however in the newer version it was renamed simply as annotate.
2. In the new version the analysis was compacted from three objects to one and the analysis flow has changed to resemble the following:

-Instantiating the fish object
fish = FishHook$new(targets = targets, events = events, eligible = eligible)
-Annotating
Note: The annotation will no longer produce a new anno onject but will modify the state of the fish object, also in the current live version there is a minor bug with patient ID column identification.
fish$annotate(maxPtGene = 1, verbose = FALSE, PtIDCol = "patient_code")
-Scoring
fish$score()

Variables may now be accessed directly using the $ operator: e.g.
fish$targets
fish$events
fish$eligible
fish$scores
fish$model
fish$all

Let me know if you have any more questions or if there are issues running any of the above. I will ping this message when the most recent updates are up.

**Comment by viktorlj** [comment]
Hi,

Thank you for the quick reply!

The new commands works perfect - thank you! Looking forward to the new manual next week for further details.

Best,
Viktor

**Comment by ZoranZG** [comment]
Update:

It looks like it will take a bit longer (Potentially this weekend) to get the newest version up with documentation, my apologies.

**Comment by ZoranZG** [comment]
Hi, so sorry I forgot about this, the newest documentation is up, see "fishHook_Demo.ipynb" for updated tutorial. Likewise, the previously mentioned bug has been patched. Once again, sorry for forgetting. Please let me know if you have any trouble with any part of fish.hook. I'll leave this issue open just in case.

**Comment by viktorlj** [comment]
Hi, thank you for notifying about this! I will look into the new documentation and will get back to you if there are further questions.

Thank you,
Viktor
